[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "github.com/pivotal-cf/brokerapi"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  branch = "master"
  name = "github.com/pmorie/go-open-service-broker-client"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
