# Default values for the minibroker
# Image to use
image: minibroker:latest
# ImagePullPolicy; valid values are "IfNotPresent", "Never", and "Always"
imagePullPolicy: IfNotPresent
deploymentPolicy: RollingUpdate
# Certificate details to use for TLS. Leave blank to not use TLS
tls:
  # base-64 encoded PEM data for the TLS certificate
  cert:
  # base-64 encoded PEM data for the private key matching the certificate
  key:

# The logging level to use; higher values emit more information
logLevel: 5

serviceCatalogEnabledOnly: true

deployServiceCatalog: false

tiller:
  version: 2.14.2
  image: helm-tiller
  registry: 
    hostname: registry.suse.com
    username: ""
    password: ""
  organization: cap

kube:
  registry:
    hostname: index.docker.io
    username: ""
    password: ""
  organization: splatform
